abstract: 'Perl Parser for GDT/BDT files of german licensed physicians.'
author:
  - Christoph Beger
dynamic_config: 0
generated_by:
license: mit
meta-spec:
  url: http://search.cpan.org/perldoc?CPAN::Meta::Spec
  version: '1.4'
name: xDT-Parser
no_index:
  directory:
    - t
build_requires:
  ExtUtils::MakeMaker: '0'
configure_requires:
  ExtUtils::MakeMaker: '0'
recommends:
  Test::Class::Moose::Load: '0.82'
requires:
  Moose: '2.2004'
  namespace::autoclean: '0.28'
  XML::Simple: '2.24'
  perl: '5.10'
release_status: unstable
version: 0.1